spring.profiles.active=${APP_ENVIRONMENT:dev}

server.servlet.context-path=/retailstore
server.port: 8080

service.name=retailstore-rest
service.version=1.0

some.properties=default-property-value

## grpahite
## management.server.port=9080
## management.endpoint.health.show-details=always
## management.endpoints.enabled-by-default=false
## management.endpoint.health.enabled=true
## management.endpoints.web.base-path=/
## spring.cloud.consul.discovery.health-check-path=/health
## spring.cloud.consul.discovery.metrics-check-path=/metrics
## management.endpoint.metrics.enabled=true

## graphite bindings
## https://docs.spring.io/spring-boot/docs/2.1.13.RELEASE/reference/html/production-ready-metrics.html#production-ready-metrics-export-graphite
## https://micrometer.io/docs/registry/statsD#_configuring
## https://micrometer.io/docs/registry/graphite
## management.endpoints.web.exposure.include=*
## management.metrics.export.graphite.enabled=true
## management.metrics.export.graphite.host=127.0.0.1
## management.metrics.export.graphite.port=2004
## management.metrics.export.graphite.step=1s
## management.metrics.export.graphite.tags-as-prefix=retailstore

### prometheus enable
## Spring Boot 4 / Micrometer 1.14+: management.metrics.export.* replaced by management.{registry}.metrics.export.*
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
management.endpoints.web.exposure.include=*

## (int) The max number of active threads in this pool, default is 200
## https://tomcat.apache.org/tomcat-11.0-doc/config/executor.html#Standard_Implementation
## https://www.baeldung.com/spring-boot-configure-tomcat
server.tomcat.threads.max=4

## Request Queue
## https://github.com/spring-projects/spring-boot/blob/v4.0.5/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/ServerProperties.java
server.tomcat.accept-count=1000000
