name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Project build
        env:
          SERVICE_VERSION: 1.0.${{ github.run_number }}
        run: ./gradlew build -x test -PprojectVersion=${SERVICE_VERSION} --build-cache

      - name: Run tests
        run: ./gradlew test jacocoTestReport

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html-report
          path: retailstore-rest-server/build/jacocoHtml/
          retention-days: 14

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/build/reports/tests/test/'
          retention-days: 14
